"""Add expenses table

Revision ID: 37080222be44
Revises: 55cea4406054
Create Date: 2023-03-21 16:39:21.995559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "37080222be44"
down_revision = "55cea4406054"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "expenses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("descriptions", sa.String(), nullable=False),
        sa.Column("amount", sa.DECIMAL(), nullable=False),
        sa.Column("time", sa.DateTime(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["group_id", "category_id"],
            ["categories_groups.group_id", "categories_groups.category_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_expenses_category_id"), "expenses", ["category_id"], unique=False
    )
    op.create_index(
        op.f("ix_expenses_group_id"), "expenses", ["group_id"], unique=False
    )
    op.create_index(op.f("ix_expenses_id"), "expenses", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_expenses_id"), table_name="expenses")
    op.drop_index(op.f("ix_expenses_group_id"), table_name="expenses")
    op.drop_index(op.f("ix_expenses_category_id"), table_name="expenses")
    op.drop_table("expenses")
    # ### end Alembic commands ###
