"""Add replenishments table

Revision ID: 66a46905b1df
Revises: 9c77e90876b0
Create Date: 2023-04-04 08:16:28.583473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "66a46905b1df"
down_revision = "9c77e90876b0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "replenishments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("descriptions", sa.String(), nullable=False),
        sa.Column("amount", sa.DECIMAL(), nullable=False),
        sa.Column("time", sa.DateTime(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_replenishments_id"), "replenishments", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_replenishments_id"), table_name="replenishments")
    op.drop_table("replenishments")
    # ### end Alembic commands ###
