"""Update expenses table

Revision ID: 9c77e90876b0
Revises: 37080222be44
Create Date: 2023-03-28 11:41:50.949645

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "9c77e90876b0"
down_revision = "37080222be44"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "expenses", "time", existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "expenses", "time", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    # ### end Alembic commands ###
