"""Add icon_url, color_code in group model

Revision ID: db2bb7068c2e
Revises: 66a46905b1df
Create Date: 2023-05-05 09:49:59.236520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "db2bb7068c2e"
down_revision = "66a46905b1df"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("groups", sa.Column("icon_url", sa.String(), nullable=False))
    op.add_column("groups", sa.Column("color_code", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("groups", "color_code")
    op.drop_column("groups", "icon_url")
    # ### end Alembic commands ###
