"""Update group and group_users table

Revision ID: dde4aa342369
Revises: f8975913cdd0
Create Date: 2023-03-14 13:42:30.825649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "dde4aa342369"
down_revision = "f8975913cdd0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("groups", sa.Column("status", sa.String(), nullable=False))
    op.add_column("user_groups", sa.Column("status", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_groups", "status")
    op.drop_column("groups", "status")
    # ### end Alembic commands ###
